# currencies.py
CURRENCY_CODES = [
    'USD - United States Dollar',
    'EUR - Euro',
    'JPY - Japanese Yen',
    'GBP - British Pound Sterling',
    'AUD - Australian Dollar',
    'CAD - Canadian Dollar',
    'CHF - Swiss Franc',
    'CNY - Chinese Yuan',
    'SEK - Swedish Krona',
    'NZD - New Zealand Dollar',
    'MXN - Mexican Peso',
    'SGD - Singapore Dollar',
    'HKD - Hong Kong Dollar',
    'NOK - Norwegian Krone',
    'KRW - South Korean Won',
    'TRY - Turkish Lira',
    'INR - Indian Rupee',
    'RUB - Russian Ruble',
    'ZAR - South African Rand',
    'BRL - Brazilian Real',
    'PLN - Polish Zloty',
    'THB - Thai Baht',
    'IDR - Indonesian Rupiah',
    'HUF - Hungarian Forint',
    'CZK - Czech Koruna',
    'ILS - Israeli New Shekel',
    'AED - United Arab Emirates Dirham',
    'MYR - Malaysian Ringgit',
    'PHP - Philippine Peso',
    'SAR - Saudi Riyal',
    'DKK - Danish Krone',
    'CLP - Chilean Peso',
    'COP - Colombian Peso',
    'PEN - Peruvian Nuevo Sol',
    'RON - Romanian Leu',
    'RSD - Serbian Dinar',
    'BGN - Bulgarian Lev',
    'HRK - Croatian Kuna',
    'MAD - Moroccan Dirham',
    'MUR - Mauritian Rupee',
    'NPR - Nepalese Rupee',
    'PKR - Pakistani Rupee',
    'TWD - New Taiwan Dollar',
    'VND - Vietnamese Dong',
    'UAH - Ukrainian Hryvnia',
    'JOD - Jordanian Dinar',
    'KWD - Kuwaiti Dinar',
    'OMR - Omani Rial',
    'BHD - Bahraini Dinar',
    'QAR - Qatari Rial',
    'CUP - Cuban Peso',
    'BAM - Bosnia and Herzegovina Convertible Mark',
    'XOF - West African CFA Franc',
    'XAF - Central African CFA Franc',
    'XPF - CFP Franc'
]
